

ALTER TABLE TEST_DB.SPRING_MVC_CRUD_APP_ENV  
ADD CONSTRAINT SPRING_MVC_CRUD_APP_ENV_PK PRIMARY KEY (ID);

ALTER TABLE TEST_DB.SPRING_MVC_CRUD_APP_VERSION  
ADD CONSTRAINT SPRING_MVC_CRUD_APP_VERSION_PK PRIMARY KEY (ID);
