
CREATE TABLE TEST_DB.SPRING_MVC_CRUD_APP_ENV (
	ID									NUMBER(5) NOT NULL ENABLE,
	ENV_CODE							VARCHAR2(5) NOT NULL ENABLE,
	ENV_NAME							VARCHAR2(20) NOT NULL ENABLE,
	CREATED_DT							TIMESTAMP(8) NOT NULL ENABLE,
	CREATED_BY							VARCHAR2(25) NOT NULL ENABLE
)	SEGMENT CREATION IMMEDIATE 
	TABLESPACE TEST_DATA ;


CREATE TABLE TEST_DB.SPRING_MVC_CRUD_APP_VERSION (
	ID									NUMBER(5) NOT NULL ENABLE,
	CODE								VARCHAR2(5) NOT NULL ENABLE,
	DESCRIPTION							VARCHAR2(25) NOT NULL ENABLE,
	VERSION								VARCHAR2(10) NOT NULL ENABLE,
	CREATED_DT							TIMESTAMP(8) NOT NULL ENABLE,
	CREATED_BY							VARCHAR2(25) NOT NULL ENABLE
)	SEGMENT CREATION IMMEDIATE 
	TABLESPACE TEST_DATA ;
