

ALTER TABLE TEST_DB.SPRING_MVC_TODO_APP_ENV  
ADD CONSTRAINT SPRING_MVC_TODO_APP_ENV_PK PRIMARY KEY (ID);

ALTER TABLE TEST_DB.SPRING_MVC_TODO_APP_VERSION  
ADD CONSTRAINT SPRING_MVC_TODO_APP_VERSION_PK PRIMARY KEY (ID);

ALTER TABLE TEST_DB.TODO_TASK  
ADD CONSTRAINT TODO_TASK_PK PRIMARY KEY (ID);
