
CREATE SEQUENCE TEST_DB.SPRING_MVC_TODO_APP_ENV_SEQ START WITH 1500 INCREMENT BY 1 NOCACHE NOCYCLE NOMAXVALUE ORDER;
CREATE SEQUENCE TEST_DB.SPRING_MVC_TODO_APP_VER_SEQ START WITH 1500 INCREMENT BY 1 NOCACHE NOCYCLE NOMAXVALUE ORDER;
CREATE SEQUENCE TEST_DB.TODO_TASK_SEQ START WITH 1500 INCREMENT BY 1 NOCACHE NOCYCLE NOMAXVALUE ORDER;
