
CREATE SEQUENCE TEST_DB.SPRING_MVC_CRUD_APP_ENV_SEQ START WITH 1500 INCREMENT BY 1 NOCACHE NOCYCLE NOMAXVALUE ORDER;
CREATE SEQUENCE TEST_DB.SPRING_MVC_CRUD_APP_VER_SEQ START WITH 1500 INCREMENT BY 1 NOCACHE NOCYCLE NOMAXVALUE ORDER;
