GRANT CONNECT to TEST_DB;

GRANT UNLIMITED TABLESPACE TO TEST_DB;

GRANT 
CREATE TABLE
,CREATE INDEXTYPE
,CREATE VIEW
,CREATE TYPE 
,CREATE SEQUENCE 
,CREATE PROCEDURE
,CREATE TRIGGER 
,CREATE PUBLIC SYNONYM
,CREATE JOB
,CREATE MATERIALIZED VIEW
,CREATE ANY CONTEXT
,DROP ANY CONTEXT
to TEST_DB;

GRANT EXECUTE ANY PROCEDURE TO TEST_DB;

